# Generated by Django 4.0.1 on 2023-04-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorOfText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardfile.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('performances', models.ManyToManyField(to='cardfile.Performance')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='performers',
            field=models.ManyToManyField(to='cardfile.Performer'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='authors_of_text',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.AuthorOfText'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='composers',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.Composer'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='cardfile.Genre'),
        ),
    ]
